spring.datasource.url=jdbc:mysql://localhost:3306/facturacion?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar ejecucion de data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
